---
- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: EA312927
  tags: install

- name: Add apt repository
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
  tags: install

- name: Install MongoDB
  apt:
    name: mongodb-org
  tags: install

- name: Configure service
  systemd:
    name: mongod
    enabled: true
  tags: install
